#!/bin/bash

# Launch this from a vnc-session or your physical host:
# > ./spawn_spec 01
#
# Currently, AHN will call to the extensions 102/103 after
# transitioning the IVR menu. If you register your softphone
# for these SIP users, it will receive the calls.
#
# You can spawn multiple firefox browsers at once:
# > ./spawn_spec 01 3

num=$1
if [ -z "$num" ]; then
  num=01
fi

times=$2
if [ -z "$times" ]; then
  times=1
fi

now=$(date +%Y%m%d-%H%M%S)

for n in $(seq 1 $times); do
  echo "Launch spec $num client $n"
  ruby ./examples/spec-$num.rb $n >./log/run-$now-$num-$n.log &
done
