#!/bin/bash

# Launch this from your physical host (audio device & firefox needed):
# > ./spawn_spec 01
#
# You can spawn multiple browsers at once:
# > ./spawn_spec 01 3

num=$1
if [ -z "$num" ]; then
  num=01
fi

times=$2
if [ -z "$times" ]; then
  times=1
fi

now=$(date +%Y%m%d-%H%M%S)

for n in $(seq 1 $times); do
  echo "Launch spec $num client $n"
  ruby ./examples/spec-$num.rb $n >./log/run-$now-$num-$n.log &
done
