#!/usr/bin/env ruby

require 'bundler'
Bundler.setup

require 'yaml'
require 'bunny'
require 'digest'
require 'active_support/all'

SpecConfig = YAML.load_file('./config/app.yml')

require './lib/amqp_manager'
require './lib/connections'
require './lib/yml_player'
require './lib/agent'
require './lib/call'
require './lib/user'

AmqpManager.start
YmlPlayer.new.start
