#!/usr/bin/env ruby

# This script simulates incoming calls by sending out
# pre-recorded messages that originally came from Voice-Ahn.
#
# It covers a lot of the Voice-stack functionality without creating
# actual SIP calls, so VoIP-related features as hangup/transfer
# are not possible.
#
# Invoke it with the number of calls to be made:
# > script/replay-events 100
#
# You may want to create some fake agents/customers before you start:
# > script/create-fake-agents
#
# When you login as admin or with the agent's credentials you will
# see the calls being queued and received.
# The number of simultaneous calls is primarily limited by the
# count of agents, because the script replays the call-sequence
# to an agent only once at a time.

require 'bundler'
Bundler.setup

require 'yaml'
require 'faker'
require 'bunny'
require 'digest'
require 'celluloid'
require 'active_support/all'

SpecConfig = YAML.load_file('./config/app.yml')
CallCount  = [1, (ARGV[0] || 1).to_i].max

require './lib/replay/remote_request'
require './lib/replay/amqp_manager'
require './lib/replay/connections'
require './lib/replay/yml_player'
require './lib/replay/customer'
require './lib/replay/agent'
require './lib/replay/call'
require './lib/replay/user'

AmqpManager.start
YmlPlayer.start(CallCount)
